# Generated by Django 4.2.6 on 2023-10-21 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRate',
            fields=[
                ('rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('sales_amount_limit', models.FloatField()),
                ('in_region_rate', models.FloatField()),
                ('out_region_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=255)),
                ('is_domestic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Salespeople',
            fields=[
                ('salesperson_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('residence', models.CharField(max_length=255)),
                ('assigned_region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesapp.region')),
            ],
        ),
        migrations.CreateModel(
            name='Use',
            fields=[
                ('use_id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_name', models.CharField(max_length=255)),
                ('usage_date', models.DateField()),
                ('salesperson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesapp.salespeople')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesapp.region')),
                ('salesperson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesapp.salespeople')),
            ],
        ),
    ]
